name: PR Label Notifier

on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Handle label add/remove and manage comments
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const number = context.payload.pull_request.number;
            const label = context.payload.label.name;

            const messages = {
              "package-request-needed": "123",
              "not-meet-criteria": "456"
            };

            const msg = messages[label];

            if (!msg) {
              return;
            }

            const comments = await github.rest.issues.listComments({
              owner,
              repo,
              issue_number: number,
            });

            const existing = comments.data.find(c =>
              c.body.trim() === msg.trim() &&
              c.user.type === "Bot"
            );

            if (!existing) {
              return;
            }

            if (context.payload.action === "labeled") {
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: number,
                body: msg
              });
              return;
            }

            if (context.payload.action === "unlabeled") {
              await github.rest.issues.deleteComment({
                owner,
                repo,
                comment_id: existing.id
              });
              return;
            }
